apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: amitesh
spec:
  selector:
    app: metabase # Must match Deployment labels
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 3000 # Container port
  type: LoadBalancer # Exposes the service externally
