apiVersion: v1
kind: Service
metadata:
  name: digital-ocean-service
  namespace: amitesh
spec:
  selector:
    app: digital-ocean # Must match Deployment labels
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 80 # Container port
  type: LoadBalancer # Exposes the service externally
